[general]
live_config_reload = true
import = ["/Users/spartan/.config/alacritty/solarized-osaka.toml"]

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#073642"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#93a1a1"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#93a1a1"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 20.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"



[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[terminal]

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95
startup_mode = "Windowed"

[window.padding]
x = 8
y = 8

[keyboard]
